import Image from "next/image";
import { Inter } from "next/font/google";
import SideNavigation from "@/components/SideNavigation";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Youtube Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link></link>
      </Head>
      <main className="flex">
        <SideNavigation />
        <h2>home page</h2>
      </main>
    </div>
  );
}
